[build]
base = "."
command = "npm run build"
publish = "./build/"

[build.environment]
DOMAIN=https://api-teste-vcodes.herokuapp.com
REACT_APP_API_URL=$DOMAIN/api/v1/
REACT_APP_API_DOCS=$DOMAIN/api-docs