[build]
base = "."
command = "npm run build"
publish = "./build/"

[build.environment]
REACT_APP_API_URL=https://api-teste-vcodes.herokuapp.com/api/v1/
REACT_APP_API_DOCS=https://api-teste-vcodes.herokuapp.com/api-docs